### ISSUE TITLE
Missing installation instructions

### ISSUE THREAD

**Issue by tot-ra** [valimised/ivxv#1]
How can I get more info on the repo? I tried make test but that doesn't work.. 
Looks like I need gradle from somewhere?
```make all
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C common/java
/Users/artjom.kurapov/git/ivxv//common/external/gradle-6.4/bin/gradle build installDist
make[1]: /Users/artjom.kurapov/git/ivxv//common/external/gradle-6.4/bin/gradle: No such file or directory
make[1]: *** [all] Error 1
make: *** [common/java] Error 2```

**Comment by tot-ra** [comment]
Would be nice to dockerize  or add  ```brew install gradle``` to development guide

**Comment by gerlion** [comment]
Hi Sven, I can't seem to find the script install_java_dep mentioned in the common/external/README.rst.
